app/models.py
from . import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    '''
    This class will contain database schema for users
    '''
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String,unique = True,nullable = False)
    email = db.Column(db.String,unique = True,nullable = False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    article = db.relationship('Article',backref='user',lazy = 'dynamic')
    comments = db.relationship('Comment',backref='user',lazy='dynamic')
    password_hash = db.Column(db.String,nullable=False)
    @property
    def password(self):
        '''
        Raises error when someone trys to read the password
        '''
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        '''
        Generates password hash
        '''
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        '''
        confirms password equal to the password hash during login
        '''
        check_password_hash(self.password_hash,password)

class Article(db.Model):
    '''
    This class will contain the database schema for articles table
    '''
    __tablename__ = 'articles'

    id = db.Column(db.Integer,primary_key = True)
    article = db.Column(db.String)
    category = db.Column(db.String)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref='article',lazy='dynamic')

    def save_article(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_article(cls):
        articles = Article.query.all()
        return articles
class Comment(db.Model):
    '''
    This class will contain the schema for comments
    '''
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(255))
    article_id = db.Column(db.Integer,db.ForeignKey('articles.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    @classmethod
    def get_comments(cls,article_id):
        comments = Comment.query.filter_by(article_id=article_id).all()
        return comments

class Quotes:
    def __init__(self,author,quote):
        '''
        Method to instanciate the quotes class
        '''
        self.author = author
        self.quote = quote

    

app/main/forms.py
from . import main
from flask_wtf import FlaskForm
from wtforms import SubmitField,StringField,TextAreaField,SelectField
from wtforms.validators import Required
from ..models import Article,Comment

class ArticleUploadForm(FlaskForm):
    article = TextAreaField('Article',validators=[Required()])
    category = StringField('Title',validators=[Required()])
    submit = SubmitField('Add Article')

class CommentsForm(FlaskForm):
    comment = TextAreaField('comment on the article',validators=[Required()])
    submit = SubmitField('Add Comment')

class UpdateProfile(FlaskForm):
    bio = StringField('About You',validators=[Required()])
    submit = SubmitField('Add Bio')

app/__init__.py
from flask import Flask
from config import configurations
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import configure_uploads,IMAGES,UploadSet

app = Flask(__name__)
db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)

def create_app(configname):
    '''
    Method for creating the app to enable for easier configurations
    '''
    app.config.from_object(configurations[configname])

    #Importing BluePrints
    from .auth import auth as auth_blueprint
    from .main import main as main_blueprint
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(main_blueprint)

    #Initialising the Importations
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from . import main
from flask import render_template,redirect,url_for,request,abort
from flask_login import login_required,current_user,login_user,logout_user
from .forms import ArticleUploadForm,CommentsForm,UpdateProfile
from .. import db,photos
from ..models import Article,Comment,User,  Quotes
from ..requests import getQuotes

@main.route('/')
def index():
    articles = Article.get_article()
    try:
        quotes = getQuotes()
    except Exception as e:
        quotes = "quotes unavailable"
    title='Welcome to the article'
    return render_template('index.html',articles=articles,quotes = quotes)

@main.route('/addarticle',methods = ['GET','POST'])
@login_required
def add_article():
    form = ArticleUploadForm()
    if form.validate_on_submit():
        article = form.article.data
        category = form.category.data
        new_article = Article(article = article,category = category,user = current_user)
        new_article.save_article()
        return redirect(url_for('.index'))
    title = 'Add a article'
    return render_template('addarticle.html',title = title,articleform = form)


@main.route('/articlediscussion/<int:article_id>/comment',methods=['POST','GET'])
@login_required
def comment(article_id):
    current_article = Article.query.filter_by(id = article_id).first()
    if request.method == "POST":
        comment = request.form.get("comment")
        new_comment = Comment(comment = comment,user = current_user,article = current_article)
        db.session.add(new_comment)
        db.session.commit()
    article = Article.query.get_or_404(article_id)
    comments = Comment.get_comments(article_id)

    title = 'Article Discussion'
    return render_template('articlediscussion.html',title = title,article = article,comments=comments)

@main.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username = username).first()
    userid = user.id
    my_articles = Article.query.filter_by(user_id = userid).all()

    if user is None:
        abort(404)

    return render_template('profile/profile.html',user = user,my_articles = my_articles)

@main.route('/user/<username>/update', methods = ['GET','POST'])
@login_required
def profle_update(username):
    user = User.query.filter_by(username = username).first()
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',username = user.username))

    return render_template('profile/update.html',form= form)

@main.route('/user/<username>/update/pic',methods= ['POST'])
@login_required
def update_pic(username):
    user = User.query.filter_by(username = username).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',username=username))

@main.route('/articlediscussion/<int:article_id>/update',methods=['POST','GET'])
@login_required
def update(article_id):
    current_article = Article.query.filter_by(id = article_id).first()
    if current_article.user != current_user:
        abort(403)
    form = ArticleUploadForm()
    if form.validate_on_submit():
        current_article.article = form.article.data
        current_article.category = form.category.data
        db.session.commit()
        return redirect('.comment',article_id = article_id)
    elif request.method == 'GET':
        form.category.data = current_article.category
        form.article.data = current_article.article
    return render_template('addarticle.html',title = 'update article',articleform = form)


@main.route('/articlediscussion/<int:article_id>/delete',methods=['POST'])
@login_required
def delete(article_id):
    current_article = Article.query.filter_by(id = article_id).first()
    if current_article.user != current_user:
        abort(403)
    db.session.delete(current_article)
    db.session.commit()
    return redirect(url_for('.index'))

app/templates/addarticle.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
            <div class="col-md-8">
                {{ wtf.quick_form(articleform) }}
            </div>
    </div>
</div>
{% endblock %}

app/templates/articlediscussion.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div>
        <div class="panel panel-default">
            <div class="panel-heading">Article</div>
            <div class="panel-body">
                <p>{{ article.article }}</p>
                <p><strong>by: {{ article.user.username }}</strong></p>
            </div>
            {% if article.user == current_user %}
                    <div>
                        <a class="btn btn-primary btn-sm sm-1"href="{{url_for('main.update',article_id = article.id)}}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm sm-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                    {% endif %}
        </div>
        <div class="row">
            <div class="col-md-6">
                    <h1>comment and feedback section</h1>
                <form action="/articlediscussion/{{article.id}}/comment" method="post">
                    <div class="form-group">
                        <input type="text" name="comment" class="form-control">
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                {% for comment in comments %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>Comment By:{{ comment.user.username }}</p>
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Article?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{url_for('.delete',article_id = article.id)}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='stylesheets/styles.css')}}">
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='stylesheets/styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="landingspot">
    <div class="container-fluid">
        <div class="textmiddle">
            <h1 style="font-family: 'Berkshire Swash', cursive;">Welcome To FlaskBlog</h1>
            <p><i>{{ quotes.quote }}</i></p>
            <p>{{ quotes.author }}</p>
            <a href="{{url_for('main.add_article')}}" class="btn btn-primary">Write An Article</a>
            <a href="{{url_for('auth.register')}}" class="btn btn-primary">Sign Up</a>
        </div>
    </div>
</div>
<div class="container-fluid">
<div class="row">
    <div>
        <h1>Article Headlines</h1>
        {% for article in articles %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">{{ article.category }}</div>
                <div class="panel-body">
                    <p>{{ article.article | truncate(200) }}</p>
                    <p><strong>{{ article.user.username }}</strong></p>
                    <a href="{{url_for('main.comment',article_id=article.id)}}" class="btn btn-primary">Read-full
                        Article</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">FlaskBlog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li style = "color:burlywood;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('main.profile',username=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {% endif %}

        </ul>
    </div>
    </div>
    </div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <img src="{{url_for('static',filename='photos/default.png')}}" alt="" class="img-thumbnail">
    
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',username=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit" class="btn btn-primary">
    </form>
      {% endif %}
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
        <a href="{{url_for('main.profle_update',username=user.username)}}" class="btn btn-primary">Edit profile</a>
    {% endif %}
  </div>
      <h1>My Articles</h1>
      {% for myarticle in my_articles %}
      <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">My Article</div>
        <div class="panel-body">
          {{ myarticle.article | truncate(200) }}
      </div>
      </div>
    </div>
      {% endfor %}
</div>
<div class="row">
    

</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <h1>Add Bio</h1>
  {{wtf.quick_form(form)}}
</div>
{% endblock %}